export const REQUEST_ID_RE = /^[A-Za-z0-9._:-]{8,128}$/;
export const GQB_PREFIX = "gqb:";
export const AUTH_PREFIX = "gqb:auth:";

export const GOAL_STATES = new Set(["running", "awaiting_owner", "blocked", "completed", "cancelled"]);
export const TASK_STATES = new Set(["pending", "active", "completed", "blocked"]);
export const DISPATCH_STATES = new Set([
  "PENDING",
  "FIRED",
  "CLAIMED",
  "CLOSED",
  "SUPERSEDED",
  "CANCELLED",
  "UNDELIVERABLE"
]);
export const LIVE_DISPATCH_STATES = new Set(["PENDING", "FIRED", "CLAIMED"]);
export const TERMINAL_DISPATCH_STATES = new Set(["CLOSED", "SUPERSEDED", "CANCELLED", "UNDELIVERABLE"]);
export const DISPATCH_KINDS = new Set(["EXECUTE", "RECOVER"]);
export const BLOCKER_KINDS = new Set([
  "OWNER_DECISION_REQUIRED",
  "DEPENDENCY_UNRESOLVED",
  "UNSAFE_PREFLIGHT",
  "CAPABILITY_UNAVAILABLE",
  "SCOPE_CONFLICT",
  "REVIEW_BOUNDARY_VIOLATION"
]);
export const EVENT_TYPES = new Set([
  "GOAL_SUBMITTED",
  "TASK_ACTIVATED",
  "ATTEMPT_OPENED",
  "DISPATCH_CREATED",
  "DISPATCH_DELIVERY_STARTED",
  "DISPATCH_FIRED",
  "DISPATCH_DELIVERY_FAILED",
  "DISPATCH_REDELIVERY_ARMED",
  "DISPATCH_CLAIMED",
  "DISPATCH_SUPERSEDED",
  "RESULT_REPORTED",
  "GATE_EVALUATED",
  "TASK_COMPLETED",
  "TASK_BLOCKED",
  "OWNER_QUESTION",
  "OWNER_DECISION",
  "GOAL_COMPLETED",
  "GOAL_CANCELLED"
]);

export const OWNER_DECISIONS = new Set([
  "ANSWER",
  "RESUME",
  "PAUSE",
  "CANCEL",
  "SUPERSEDE_ATTEMPT",
  "AUTHORIZE_DISPATCH",
  "REVOKE_DISPATCH_AUTHORIZATION",
  "RAISE_ATTEMPT_CEILING"
]);

export const CONTROL_KINDS = new Set([
  "PAUSE",
  "CANCEL",
  "AUTHORIZE_DISPATCH",
  "REVOKE_DISPATCH_AUTHORIZATION",
  "RAISE_ATTEMPT_CEILING"
]);

export const DETERMINISTIC_UPSTREAM_ERROR_MAP = new Map([
  ["VALIDATION_ERROR", "INVALID_ARGUMENT"],
  ["INVALID_REQUEST_ID", "INVALID_ARGUMENT"],
  ["INVALID_TASK_PLAN", "INVALID_ARGUMENT"],
  ["GOAL_NOT_FOUND", "UPSTREAM_REFUSED"],
  ["KIND_STATE_MISMATCH", "KIND_STATE_MISMATCH"],
  ["ATTEMPT_BUDGET_EXHAUSTED", "ATTEMPT_BUDGET_EXHAUSTED"],
  ["ATTEMPT_CEILING_AT_BOUND", "ATTEMPT_CEILING_AT_BOUND"],
  ["ACTIVE_GOAL_EXISTS", "ACTIVE_GOAL_EXISTS"],
  ["UNKNOWN_OWNER_DECISION_KIND", "INVALID_ARGUMENT"]
]);

export const EFFECT_STATUS = Object.freeze({
  APPLIED: "APPLIED",
  ALREADY_APPLIED_OR_NOOP: "ALREADY_APPLIED_OR_NOOP",
  NOT_APPLIED: "NOT_APPLIED",
  INDETERMINATE: "INDETERMINATE"
});

export const JOURNAL_PHASE = Object.freeze({
  INTENT: "INTENT",
  OUTCOME: "OUTCOME",
  RECONCILED: "RECONCILED"
});

export const CHANNEL = Object.freeze({
  LOCAL_SOCKET: "LOCAL_SOCKET",
  PUBLIC_DECLARED: "PUBLIC_DECLARED"
});
